### ISSUE TITLE
Installation fails: conda, pip, Python 2

### ISSUE THREAD

**Issue by Uiuran** [Technologicat/pyan#13]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-PPzXEv/setup.py", line 97
        print("WARNING: Version information not found in '%s', using placeholder '%s'" % (init_py_path, version), file=sys.stderr)
                                                                                                                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-PPzXEv/

Pip 19.1.1
Conda 4.6.14

**Comment by Technologicat** [comment]
Ok. What is the Python version?

**Comment by Uiuran** [comment]
2.7.16

**Comment by Technologicat** [comment]
Ah, that explains it. The Pyan package in PyPI requires Python 3 (tested on 3.4 and 3.6). It also only analyzes Python 3 code.

This is because support for Python 2 will in any case [end on January 1, 2020](https://pythonclock.org/). The compiler interface in the standard library is quite different between Python 2 and 3, so when I added Python 3 support to Pyan, Python 2 support unfortunately had to go.

For analyzing Python 2 code, you can use the final version of Pyan for Python 2, archived in @davidfraser's repo:

https://github.com/davidfraser/pyan/tree/pre-python3

It's just a single .py file, needs no installation. If you'd like to have a `pyan` command, like in the new version: copy `pyan.py` to somewhere along your `PATH`, rename that copy as just `pyan` (no `.py`), and then `chmod +x pyan` it to mark it as executable.
