### ISSUE TITLE
Set up pyan3 as an entrypoint

### ISSUE THREAD

**Issue by Technologicat** [Technologicat/pyan#23]
The recommended way to set up command-line scripts is nowadays using the `entry_points` option of `setup.py`.

The `pyan3` wrapper script should be replaced by a `setup.py` entrypoint named `pyan3`, pointing to `pyan.main:main`, to ensure the wrapper will work everywhere command-line Python does.

See e.g. [Python project maturity checklist](http://michal.karzynski.pl/blog/2019/05/26/python-project-maturity-checklist/) by Michał Karzyński.

**Comment by johnyf** [comment]
The name `pyan3` has been used for the script in #33. There is one package named [`pyan3` on PyPI](https://pypi.org/project/pyan3/) and [no package named `pyan` on PyPI](https://pypi.org/project/pyan/). [Python 2.7 reached its EOL on Jan 1 2020](https://www.python.org/doc/sunset-python-2/). Python 3 is the current version of the Python language. I would recommend that the entry point be named `pyan`, instead of `pyan3`, so that users would have to type and remember less.

Also, the package itself could be released as `pyan` on PyPI, instead of `pyan3` (and the entry of `pyan3` could even be removed, though this may cause backward compatibility issues with users).
