### ISSUE TITLE
Asserts can be removed during bytecode optimization

### ISSUE THREAD

**Issue by edumco** [Technologicat/pyan#29]
From Codacy issues

> assert is removed with compiling to optimised byte code (python -o producing *.pyo files). This caused various protections to be removed. The use of assert is also considered as general bad practice in OpenStack codebases.

Link to list all occurrences:
[https://app.codacy.com/manual/edumco/pyan/issues/index?bid=15369107](https://app.codacy.com/manual/edumco/pyan/issues?bid=15369107&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE5NDkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==)

**Comment by edumco** [comment]
Github suggested this issue #18 as a similar bug. And it looks promissing because it only happens on runtime.

**Comment by Technologicat** [comment]
Thanks for the report!

As for #18, there's a bug somewhere in the algorithm that populates the graph. A helpful, minimal working example has been posted, so it shouldn't be too difficult to figure out what is happening there, once I have a couple of hours to dedicate to that. I suspect it's unrelated to the asserts - or if anything, we're missing an assert somewhere, to [fail-fast](https://en.wikipedia.org/wiki/Fail-fast) the particular assumption violation that currently bubbles up until it causes a visible failure much later (likely far away from its original cause).

I've just been ~lazy~ [away from Pyan](https://github.com/Technologicat/unpythonic) for a while, so I haven't looked at it in detail yet, beside what I already wrote in the comments to #18.

As for asserts in general, I just happen to come from a different school. This is a multifaceted issue requiring an essay answer, so please bear with me. :)

IMHO, the `assert cond` construct itself is neither bad nor good - that depends on how it's used. (Unlike, say, unrestricted `goto`, which is inherently [harmful](https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf), because it fundamentally makes it impossible to locally reason about control flow. [As Nathaniel Smith has pointed out](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/), `goto` has a parallel (pun not intended) in many popular concurrent programming schemes; his [trio](https://trio.readthedocs.io/en/stable/) library is (AFAIK) one of the first attempts to build something that makes concurrent code easier to reason about - by eliminating unrestricted `go`, much like modern languages have eliminated unrestricted `goto`. What I mean by *unrestricted* is that there are still some *restricted* forms of `goto`, even in Python - `break`, `continue`, `return` and `raise` all transfer control, but only outward on the call stack.)

The `assert cond` construct is, fundamentally, merely convenient shorthand for the more verbose `if not cond: raise AssertionError` (in essence it's a very specific [syntactic macro](https://en.wikipedia.org/wiki/Macro_(computer_science)#Syntactic_macros)!). With readability equal ([no golfing](https://en.wikipedia.org/wiki/Code_golf)!), shorter code has fewer places for bugs to hide, and is faster to read (by humans), so the shorthand should be preferred over the longhand form. The shorthand also comes with the bonus of explicitly telling the compiler it is an assert, so the compiler knows to omit it from the bytecode output should the user request to do so.

(Code density concerns aside, it bears pointing out that shorter is better still only up to a point. As Paul Graham argues in [On Lisp](http://paulgraham.com/onlisp.html), there is a learning cost associated with each new construct. A shorthand, if a new construct is defined locally in a project, it should save at least several times the length of the longhand form (when amortized over the whole codebase), before defining the shorthand becomes an overall win. Here the learning cost is negligible, because `assert` is part of the base language, so anyone programming in Python is likely already aware of it.)

Codacy (new to me - thanks for the link, by the way!) correctly points out that asserts may end up removed from a production compile, implying that the code must be safe to run even if the asserts aren't there. Up to this point, I agree.

But I think asserts are still useful. I see their role as helping to catch violations of [preconditions and postconditions](https://en.wikipedia.org/wiki/Programming_by_contract) at development time, as well as explicitly documenting such assumptions in a form that can be (optionally) machine-checked. Correct usage is to only assert on conditions that - in the absence of bugs - are always true. For things to which Murphy's law may apply at runtime (to paraphrase [Peter Seibel](http://www.gigamonkeys.com/book/beyond-exception-handling-conditions-and-restarts.html)), exceptions or another error handling mechanism (including *conditions and restarts* in Common Lisp, and the `Either` monad in Haskell) are the appropriate tools.

I think using asserts to enforce preconditions and postconditions is similar to using [mypy](http://mypy-lang.org/) for enforcing type safety. During development, certain safety checks are enabled, and in production, they are disabled, allowing the program to run a bit faster. This general pattern is very common - for example, [Cython has compiler directives](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) to disable bounds checking and wraparound (a.k.a. negative indexing) for array accesses.

Ideally, for checking preconditions and postconditions, I'd like a Turing-complete [contract system](https://docs.racket-lang.org/reference/contracts.html), but... in a way, a general-purpose programming language itself already is one (the value of a specialized contract system being in the brevity and uniformity of notation). For most everyday uses, asserts at entry/exit points perform this job just fine.

Granted, there are (mathematical/logical) properties that are better captured in a static representation one meta-level higher, because the halting problem and its cousins make it impossible, in general, to dynamically check for things such as "is this sequence finite?". But in any sufficiently flexible language, it's just a design choice of which properties to encode in the concept of static type, versus which ones to dynamically verify at runtime.

Python actually already has something resembling this distinction - the language is fully duck-typed, but then there are things like the metaclasses in `collections.abc`, their generalization [`typing.Protocol`](https://docs.python.org/3/library/typing.html#typing.Protocol), mypy... and indeed, classes themselves (even, with [The Right Way](https://en.wikipedia.org/wiki/C3_linearization) to handle multiple inheritance!), if one chooses to subscribe to the (very un-ducklike) notion of nominative (as opposed to structural) typing. I suppose both kinds of typing are just tools, with different strengths and weaknesses.

(It's not the only such "mismatch" between how Python presents itself at the surface, and how it actually works or what can be done with it. Python is actually flexible enough [to support syntactic macros](https://github.com/azazel75/macropy), although they are not commonly used. [Python's object model is actually prototype-based](https://eev.ee/blog/2017/11/28/object-models/), just like JavaScript's, even though it attempts to look like a traditional class-based system (possibly to avoiding confusing those coming from C++ or Java?). In ES6, [JS went the same route](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), too.)

Anyway, to return to the main topic of asserts, I think I understand where Codacy is coming from. Python advertises itself as a language for programmers of all skill levels, valuing clarity foremost. The `assert` construct is particularly easy to misuse, unless one is careful. It's a deceptively simple-looking advanced feature (I'd argue comments are, too...).

So to make a codebase easily approachable to the largest possible audience, it's safer if the code doesn't use asserts, so it's easier to resist the temptation to "follow the example" and add in some inadvertently incorrect ones when working on it.

If that is the reasoning behind the recommendation, my answer is more education for the general programming audience. I admit I don't know how well that scales. :)

Further thoughts welcome - including, and especially, opposing viewpoints.

**Comment by edumco** [comment]
I am incredbly happy with your answer, because it not only make me understand this issue more profoundly as it opens a whole new perspective on the language itself.

I never really understood (this deep) the use of assertions outside the tests.

Any tool we could use to enhance our code to me is a good thing and in this context appears to me that it is used exactly for that.

I'm a great fan of Codacy and other code analyzers because they put question on your head about the code you're producing, but it should never be used as bible. And this discussion (talk/conversation I'm no native english speaker) tackle so many things that i'm gonna need a few weeks to fully grasp all this richness.

You explain things very well! I think you should publish this conversation somewhere else.

Thank you a lot and a big hug from Brazil!

PS: I'm going to ignore this issues for this repo :)

**Comment by Technologicat** [comment]
Glad I could help. Yes, I might need a blog instead of using GitHub issue comments as such... :)

Here are some more ideas and/or pointers that may interest you, or indeed anyone who ends up here via Google:

- Regarding `assert` in tests, with Python supporting [import hooks](https://docs.python.org/3/reference/import.html#import-hooks), the `assert` statement has become an obvious place to attach test frameworks.
  - [`pytest`](https://docs.pytest.org/en/latest/) does this, so in your tests, you just write `assert` statements as usual. But instead of your tests stopping at the first error, `pytest` proceeds even if an assert fails, and gives you a nice report at the end.
  - I haven't looked at how they do it, but if I had to do it, I'd use import hooks to transform the [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) of the module containing the test code, at import time. If this sounds a lot like syntactic macros, it's because it is. Macropy also transforms the AST at import time, but lets the user control what gets transformed into what. This can be used to build [new language constructs](https://github.com/Technologicat/unpythonic/blob/master/doc/macros.md).
  - Metaprogramming with syntactic macros is common in the Lisp family of programming languages, less so elsewhere. It's a powerful technique, but it does introduce its fair share of new technical difficulties. (Many of which you'll figure out, if you think through the logical implications of what the macro expander does: in the AST, it replaces the macro invocation by the equivalent expanded code. A macro is essentially just shorthand for some longhand piece of code; or more generally, a procedure that takes some high-level specification and generates that longhand code from it. Exercise: consequences of variable name conflicts between the macro expansion and the use site? Can macros be first-class objects?)
- Static analyzers are indeed a nice productivity booster.
  - I use [flake8](https://flake8.pycqa.org/en/latest/user/configuration.html), which integrates into [Spacemacs](https://www.spacemacs.org/). It's a combination of [pyflakes](https://github.com/PyCQA/pyflakes)-style static analysis with [PEP8](https://www.python.org/dev/peps/pep-0008/) code style checking.
  - [autopep8](https://pypi.org/project/autopep8/) is useful, too. Integrates into Spacemacs, too, so when I save a `.py` file, it gets PEP8 enforced automatically. :)
  - Both of these tools have configuration options, so you can choose which rules to enforce, and which ones to ignore. (Here's [the big list of rules](https://lintlyci.github.io/Flake8Rules/).) IMHO, some things in PEP8 are just silly - two blank lines after each function body wastes vertical space, if you have many short functions, like the [functional programming](https://en.wikipedia.org/wiki/Functional_programming) style tends to produce.
  - If you're curious, [my configs are on GitHub](https://github.com/Technologicat/spacemacs.d/). The `flake8` config file works with both `flake8` and `autopep8`. (You probably already have them set up?)
- Some recommended readings, if you want to explore programming language design further:
  - [Fear of Macros](http://www.greghendershott.com/fear-of-macros/): Greg Hendershott's primer on understanding syntactic macros.
  - [Structural insight](https://fexpr.blogspot.com/), John Shutt's blog. He's the author of a Lisp dialect called [Kernel](http://lambda-the-ultimate.org/node/1680). For a taste, see the essay on [Abstractive power](https://fexpr.blogspot.com/2013/12/abstractive-power.html).
  - [Stupid Python Ideas](https://stupidpythonideas.blogspot.com/). For a taste, [Hacking Python without hacking Python](https://stupidpythonideas.blogspot.com/2015/06/hacking-python-without-hacking-python.html).
  - [Lambda the Ultimate](http://lambda-the-ultimate.org/), a discussion forum on programming language design. Participants tend to be well-informed. For example, here's [a thread on type systems](http://lambda-the-ultimate.org/node/220).
  - [Matthew Might's blog](http://matt.might.net/articles/). His slogan is *to understand is to implement*. For example, [You don't understand exceptions, but you should](http://matt.might.net/articles/implementing-exceptions/). See also [Compiling to lambda-calculus: Turtles all the way down](http://matt.might.net/articles/compiling-up-to-lambda-calculus/).
    - So also, to learn language design, take a page from him, and just build something. I recommend [Racket](https://racket-lang.org/) as a particularly friendly, pythonic Lisp dialect that's specifically geared for experimenting with language ideas. It gives you all the infrastructure for free, so you can concentrate on the interesting parts.
      - [The Racket Guide](https://docs.racket-lang.org/guide/index.html) is friendly and a nice starting point.
      - See also [Beautiful Racket](https://beautifulracket.com/), an online book by Matthew Butterick.
      - I tested Racket briefly myself; [here are some code experiments](https://github.com/Technologicat/python-3-scicomp-intro/tree/master/examples/beyond_python).
      - True wizards implement things like [this](https://lexi-lambda.github.io/blog/2015/12/21/adts-in-typed-racket-with-macros/) and [this](https://github.com/tonyg/racket-monad).
    - If you want to experiment with language design in Python, consider Macropy (PyPI package `macropy3`). Note [the correct fork](https://github.com/azazel75/macropy) if you want the latest code. [The documentation](https://macropy3.readthedocs.io/en/latest/) is friendly, but having some experience with Common Lisp's `defmacro` or with Racket's `syntax-parse` helps here. Since the Lisp family is "the native habitat" of syntactic macros, learning the basics there first is simpler than learning them directly in Python.
- Design by contract (DbC) is not nearly as well-known as it, IMHO, should be. For me it was an eye-opener when I first heard about it years back.
  - In my experience, many programmers tend to focus on static types instead of the more general idea of contracts.
  - The very rudimentary static type system in low-level languages such as C is so useless it may give static type systems a bad name. Let's talk [parametric polymorphism](https://en.wikipedia.org/wiki/Parametric_polymorphism) or [Hindley-Milner](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system), and then we're starting to have a system that actually helps.
  - [Gradual typing](https://en.wikipedia.org/wiki/Gradual_typing) is a related idea. [Typed Racket](https://docs.racket-lang.org/ts-guide/) has it, as well as [Julia](https://julialang.org/), and arguably Mypy (though in Mypy specifying types doesn't help performance; [that's not in its design goals](https://mypy.readthedocs.io/en/stable/faq.html#how-is-mypy-different-from-cython)).
- Final practical tip: Feeling adventurous? Want faster Python? Try [PyPy](https://www.pypy.org/). Nowadays it supports version 3.6 of the Python language, and runs even complicated libraries such as SciPy just fine...
